#!/bin/bash 

PLATFORM=$1
ACTION=$2
EXTRA=$3

if [ "$1" = "" ]
then
  clear
  echo "Expresso"
  echo "----------------------------------------"
  echo ""
  echo "Exemplos de uso"

    echo "  - expresso android debug"
	echo "  - expresso android run "
	echo "  - expresso android release 1.x"
	echo "  - expresso web dist"
	echo "  - expresso web release 1.x"
	echo "  - expresso web publish Teste"
	echo " "
	echo " "
fi
# expresso android debug
# expresso android run 
# expresso android release 1.0.2
# expresso web dist
# expresso web release 1.0.2
# expresso web publish "Teste"

if [ "$1" = "android" ]
then

	if [ "$2" = "run" ]
	then
		echo "EXPRESSO - ANDROID - RUN"
		./hooks/gen_dist.sh
		cordova run android
	fi

	if [ "$2" = "build" ]
	then
		echo "EXPRESSO - ANDROID - BUILD"
		cordova build android
	fi

	if [ "$2" = "debug" ]
	then
		echo "EXPRESSO - ANDROID - DEBUG"
		echo "COPIANDO A PASTA SOURCE PARA A WWW"
		rm -rf ./www/
		mkdir ./www
		touch ./www/.empty
		cp -R ./source/ ./www/
		echo "COMPILANDO PROJETO ANDROID"
		cordova run android
	fi
    
    if [ "$2" = "release" ]
	then

		echo "EXPRESSO - ANDROID - RELEASE"
		cordova build android --release
		mkdir ./releases/android/$EXTRA
		cp -R ./platforms/android/build/outputs/apk/android-release-unsigned.apk ./releases/android/$EXTRA/Expresso-unaligned.apk

		jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ./platforms/android/celepar_expresso_keystore ./releases/android/$EXTRA/Expresso-unaligned.apk celepar
		rm ./releases/android/$EXTRA/Expresso.apk

		/projeto/frameworks/android-sdk-mac_x86/build-tools/21.1.2/zipalign  -v 4 ./releases/android/$EXTRA/Expresso-unaligned.apk ./releases/android/$EXTRA/Expresso.apk

		echo "ARQUIVO APK DA RELEASE $EXTRA NA PASTA:"
		echo "./releases/android/$EXTRA/Expresso.apk"
	fi
    
fi

if [ "$1" = "web" ]
then
	if [ "$2" = "dist" ]
	then
		echo "EXPRESSO - WEB - DIST"
		./hooks/gen_dist.sh
	fi

	if [ "$2" = "publish" ]
	then
		echo "EXPRESSO - WEB - PUBLISH"
		./hooks/publish_release.sh "$EXTRA"
	fi

	if [ "$2" = "release" ]
	then
		echo "EXPRESSO - WEB - RELEASE"
		./hooks/gen_dist.sh
		mkdir ./releases/web/$EXTRA
		cp -R ./www/ ./releases/web/$EXTRA/
	fi
fi